"""Frozen schema operations used by the production persistence baseline."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql


def create_schema() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('risk_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=True),
    sa.Column('policy_key', sa.String(length=100), nullable=False),
    sa.Column('policy_value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_risk_policies_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_policies')),
    sa.UniqueConstraint('portfolio_id', 'policy_key', name=op.f('uq_risk_policies_portfolio_id'))
    )
    with op.batch_alter_table('risk_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_policies_policy_key'), ['policy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_policies_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_watchlists_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists'))
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlists_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=True),
    sa.Column('replay_of', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('scenario', sa.String(length=48), nullable=False),
    sa.Column('agent_provider', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_decision', sa.String(length=30), nullable=True),
    sa.Column('final_confidence', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('legacy_data', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_workflow_runs_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replay_of'], ['workflow_runs.id'], name=op.f('fk_workflow_runs_replay_of_workflow_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_final_decision'), ['final_decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_replay_of'), ['replay_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_updated_at'), ['updated_at'], unique=False)

    op.create_table('agent_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bullish_factors', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bearish_factors', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('risk_flags', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('suggested_position_pct', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('suggested_stop_loss_pct', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('suggested_take_profit_pct', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('invalidation_conditions', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_agent_decisions_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_decisions')),
    sa.UniqueConstraint('workflow_run_id', 'agent_name', name=op.f('uq_agent_decisions_workflow_run_id'))
    )
    with op.batch_alter_table('agent_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_decisions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decisions_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decisions_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decisions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decisions_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_audit_events_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('consensus_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('agreement_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('disagreement_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('agreeing_agents', sa.Integer(), nullable=False),
    sa.Column('total_agents', sa.Integer(), nullable=False),
    sa.Column('supporting_agents', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dissenting_agents', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_consensus_decisions_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consensus_decisions'))
    )
    with op.batch_alter_table('consensus_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consensus_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consensus_decisions_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_consensus_decisions_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('execution_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('client_order_id', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('time_in_force', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('notional', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('risk_decision', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_response', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_execution_orders_workflow_run_id_workflow_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_orders')),
    sa.UniqueConstraint('provider_order_id', name=op.f('uq_execution_orders_provider_order_id'))
    )
    with op.batch_alter_table('execution_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_orders_client_order_id'), ['client_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_execution_orders_filled_at'), ['filled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_orders_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_orders_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_orders_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('explanations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('final_action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('positive_factors', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('negative_factors', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('agent_votes', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('consensus_explanation', sa.Text(), nullable=False),
    sa.Column('risk_decision', sa.String(length=30), nullable=False),
    sa.Column('triggered_rules', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requested_size', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('approved_size', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('invalidation_conditions', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_explanations_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explanations'))
    )
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explanations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_explanations_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bars', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_market_snapshots_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots'))
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('news_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('relevance', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('corroborated', sa.Boolean(), nullable=False),
    sa.Column('duplicate_group', sa.String(length=255), nullable=True),
    sa.Column('information_risk', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_news_items_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_items'))
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('account_status', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('day_pl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('day_pl_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('portfolio_drawdown_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('open_orders', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_portfolio_snapshots_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('risk_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=30), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('measured_value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('threshold_value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_risk_checks_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_checks')),
    sa.UniqueConstraint('workflow_run_id', 'rule_id', name=op.f('uq_risk_checks_workflow_run_id'))
    )
    with op.batch_alter_table('risk_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_checks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_checks_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_checks_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_checks_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_checks_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('risk_gate_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('requested_position_pct', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('approved_position_pct', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('reasons', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_risk_gate_results_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_gate_results'))
    )
    with op.batch_alter_table('risk_gate_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_gate_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_gate_results_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_gate_results_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('risk_reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=False),
    sa.Column('semantic_risk_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('issues', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_risk_reviews_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_reviews'))
    )
    with op.batch_alter_table('risk_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_reviews_verdict'), ['verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_reviews_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('soc_alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('rule_id', sa.String(length=30), nullable=False),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_soc_alerts_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soc_alerts'))
    )
    with op.batch_alter_table('soc_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soc_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_soc_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_soc_alerts_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_soc_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_soc_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_soc_alerts_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_soc_alerts_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('trade_proposals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('consensus_confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('requested_position_pct', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('requested_notional', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('approved_position_pct', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('approved_notional', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('risk_decision', sa.String(length=30), nullable=True),
    sa.Column('stop_loss_pct', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('take_profit_pct', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('supporting_agents', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dissenting_agents', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('invalidation_conditions', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_trade_proposals_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_proposals'))
    )
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_workflow_run_id'), ['workflow_run_id'], unique=True)

    op.create_table('watchlist_symbols',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('watchlist_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_symbols_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_symbols')),
    sa.UniqueConstraint('watchlist_id', 'symbol', name=op.f('uq_watchlist_symbols_watchlist_id'))
    )
    with op.batch_alter_table('watchlist_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_symbols_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_symbols_watchlist_id'), ['watchlist_id'], unique=False)

    op.create_table('workflow_errors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_errors_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_errors'))
    )
    with op.batch_alter_table('workflow_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_errors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_errors_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('portfolio_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unrealized_pl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unrealized_pl_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_snapshot_id'], ['portfolio_snapshots.id'], name=op.f('fk_positions_portfolio_snapshot_id_portfolio_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_positions_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_portfolio_snapshot_id'), ['portfolio_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_workflow_run_id'), ['workflow_run_id'], unique=False)

    # ### end Alembic commands ###


def drop_schema() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_portfolio_snapshot_id'))

    op.drop_table('positions')
    with op.batch_alter_table('workflow_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_errors_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_errors_created_at'))

    op.drop_table('workflow_errors')
    with op.batch_alter_table('watchlist_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_symbols_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_symbols_symbol'))

    op.drop_table('watchlist_symbols')
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_proposals_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_created_at'))

    op.drop_table('trade_proposals')
    with op.batch_alter_table('soc_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soc_alerts_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_soc_alerts_symbol'))
        batch_op.drop_index(batch_op.f('ix_soc_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_soc_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_soc_alerts_rule_id'))
        batch_op.drop_index(batch_op.f('ix_soc_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_soc_alerts_alert_type'))

    op.drop_table('soc_alerts')
    with op.batch_alter_table('risk_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_reviews_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_risk_reviews_verdict'))

    op.drop_table('risk_reviews')
    with op.batch_alter_table('risk_gate_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_gate_results_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_risk_gate_results_decision'))
        batch_op.drop_index(batch_op.f('ix_risk_gate_results_created_at'))

    op.drop_table('risk_gate_results')
    with op.batch_alter_table('risk_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_checks_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_risk_checks_severity'))
        batch_op.drop_index(batch_op.f('ix_risk_checks_rule_id'))
        batch_op.drop_index(batch_op.f('ix_risk_checks_passed'))
        batch_op.drop_index(batch_op.f('ix_risk_checks_created_at'))

    op.drop_table('risk_checks')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_captured_at'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_account_id'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_news_items_symbol'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_external_id'))

    op.drop_table('news_items')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_snapshot_time'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explanations_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_explanations_created_at'))

    op.drop_table('explanations')
    with op.batch_alter_table('execution_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_orders_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_execution_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_execution_orders_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_execution_orders_status'))
        batch_op.drop_index(batch_op.f('ix_execution_orders_filled_at'))
        batch_op.drop_index(batch_op.f('ix_execution_orders_client_order_id'))

    op.drop_table('execution_orders')
    with op.batch_alter_table('consensus_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consensus_decisions_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_consensus_decisions_direction'))
        batch_op.drop_index(batch_op.f('ix_consensus_decisions_created_at'))

    op.drop_table('consensus_decisions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    with op.batch_alter_table('agent_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_decisions_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decisions_symbol'))
        batch_op.drop_index(batch_op.f('ix_agent_decisions_input_hash'))
        batch_op.drop_index(batch_op.f('ix_agent_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_decisions_agent_name'))
        batch_op.drop_index(batch_op.f('ix_agent_decisions_action'))

    op.drop_table('agent_decisions')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_symbol'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_replay_of'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_final_decision'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_completed_at'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_watchlists_created_at'))

    op.drop_table('watchlists')
    with op.batch_alter_table('risk_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_policies_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_risk_policies_policy_key'))

    op.drop_table('risk_policies')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_created_at'))

    op.drop_table('portfolios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
